project:
  type: website

website:
  title: "Dengue Data Hub"
  google-analytics: "UA-262479182"
  navbar:
    right:
      - about.qmd
      - Data.qmd
      - world.qmd
      - srilanka.qmd
      - singapore.qmd
      - china.qmd
      - commonfunctions.qmd
      - viz.qmd
      - vizinteractive.qmd
      - collaborate.qmd
      - icon: github
        href: https://github.com/thiyangt
      - icon: twitter
        href: https://twitter.com/thiyangt
format:
  html:
    page-layout: full
    theme: yeti
    css: style.css



