project:
  type: website

website:
  title: "Dengue Data Hub"
  google-analytics: "UA-262479182"
  navbar:
    right:
      - about.qmd
      - Data.qmd
      - world.qmd
      - srilanka.qmd
      - singapore.qmd
      - china.qmd
      - viz.qmd
      - commonfunctions.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: yeti
    css: styles.css

  


