---
title: "China"
toc: true
format:
  html:
    theme: default
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-MMF7S9CQZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-MMF7S9CQZW');
</script>

# Annual Dengue Cases from 2005 to 2020

```{r, message=FALSE, warning=FALSE}
library(denguedatahub)
library(tsibble)
china_annual_data
```

## Visualize `china_annual_data`

```{r}
visdat::vis_dat(china_annual_data)
```

# Applications

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(magrittr)
library(plotly)

data <- china_annual_data %>% pivot_longer(cols=2:5, names_to = c("type"), values_to = c("count"))
data                                           
p1 <- ggplot(data, aes(x=year, y=count, group=type)) +
  geom_line(aes(col=type)) + geom_point(aes(col=type)) +
  scale_x_continuous(breaks=seq(2005, 2020, 1)) + scale_fill_brewer(palette = "Dark2") +  theme(legend.position = "bottom") 
#plotly::ggplotly(p1) %>%
#  layout(legend = list(
#      orientation = "h"
#    )
#  )
p1
```