---
title: "Singapore"
toc: true
format:
  html:
    theme: default
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-MMF7S9CQZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-MMF7S9CQZW');
</script>

# Weekly Dengue Cases in Singapore from 2018 to 2023

```{r, warning=FALSE, message=FALSE}
library(denguedatahub)
library(tsibble)
singapore_weekly_data
```

# Visualizing `singapore_weekly_data`

```{r}
visdat::vis_dat(singapore_weekly_data)
```


# Visualizations of temporal patterns

```{r, comment=NA, message=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(plotly)

p1 <- ggplot(singapore_weekly_data, aes(x=as.factor(week), y=cases, col=as.factor(year), group=year)) +
  geom_line() + geom_point() + xlab("week") + 
  scale_color_discrete(name="Year") +  theme(legend.position="bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p1
```
