---
title: "Sri Lanka"
toc: true
format:
  html:
    theme: default
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-MMF7S9CQZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-MMF7S9CQZW');
</script>

# District-wise weekly Dengue cases from 2006 to 2023-present

```{r, echo=TRUE, eval=TRUE}
library(denguedatahub)
srilanka_weekly_data

```

## Visualize `srilanka_weekly_data`

```{r}
visdat::vis_dat(srilanka_weekly_data)
```

## Time series visualization 

```{r, warning=FALSE, message=FALSE, fig.height=20, fig.width=15}
library(plotly)
library(viridis)

#  Visualizing colombo district cases
number_ticks <- function(n) {function(limits) pretty(limits, n)}
srilanka_weekly_data %>%  
ggplot(aes(x=start.date, y=cases)) + geom_line()  + 
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_wrap(vars(district), scales = "free_y", ncol=5)


```

# Function to extract dengue cases from weekly epidemiological reports published by [Epidemiology Unit, Ministry of Health Sri Lanka](https://www.epid.gov.lk/web/index.php?option=com_content&view=article&id=148&Itemid=449&lang=en)

```{r, warning=FALSE, message=FALSE, eval=FALSE}
ad.list <- get_addresses("http://www.epid.gov.lk/web/index.php?option=com_content&view=article&id=148&Itemid=449&lang=en")
wer2023url <- filter_year_wer(2023, ad.list[1:9])
data2023 <- convert_srilanka_wer_to_tidy(year=2023, url.part2=wer2023url, 
start.date.first = "2022-12-31",
end.date.first = "2023-01-06",
start.date.last = "2023-01-28", 
end.date.last = "2023-02-03",
week.no=c(52, 1:4))
data2023
```
